### ISSUE TITLE
not working with IE11 : badly transpiled

### ISSUE THREAD

**Issue by pmnc-philippe** [shianqi/cache-manager-web#1]
line 36 in /lib/index.js
  self.store = require(`./stores/${storeName}.js`).default.create(args);

This quote template is ES6 and not supported by IE11.

would it be possible to get a fix ?

**Comment by shianqi** [comment]
@pmnc-philippe Thanks for raising issues, this problem has been fixed in v0.1.1, you can install the latest version to use
